name: Build with Gulp and deploy to AWS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@main

    - name: Use Node.js 20.x
      uses: actions/setup-node@main
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        gulp

    - name: Deploy
      run: ./deploy.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        CDN_DISTRIBUTION_ID: ${{ secrets.CDN_DISTRIBUTION_ID }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
